config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def design
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag "icons/favicon_logo.ico" %>
  <title>Caitlin Daitch || Full-Stack Web Developer</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/projects/index.html.erb
<header>
  <nav>
    <div class="nav-item"><a href="#portfolio" class="z-depth-1">Portfolio</a></div>
    <div class="nav-item"><a href="#about" class="z-depth-1">About Me</a></div>
  </nav>
  <h1>
    <div class="first-name">Caitlin</div>
    <div class="last-name">Daitch</div>
  </h1>
  <div class="description">
    Front-End Developer at <a href="http://www.fundrise.com">Fundrise</a>. Design nerd. New Wave Enthusiast.
  </div>
</header>
<container>
  <div class="section-header" id="portfolio">
    <h2>Portfolio</h2>
  </div>
  <div class="row">
    <div id="portfolio" class="row">
      <% @projects.each do |project| %>
        <div class="col m2 s12">
          <div class="image-container">
            <%= link_to image_tag(project.thumbnail, :class => "thumbnail"), project_path(project) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</container>

<container>
  <div class="section-header" id="about">
    <h2>About Caitlin</h2>
  </div>
  <div class="row">
    <div class="col m3 s12">
      <%= image_tag("caitlin_fundrise.jpg", :class => "headshot") %>
    </div>
    <div class="col m9 s12 about-description">
      <p>I have been interested in programming and design since middle school when I spent my free time building websites for fun. Years later, I hit the jackpot when I was offered a position as a Digital Producer for a web development agency in Washington, DC. Working as a project manager for all things digital ultimately solidified my passion for web development. I fell in love with programming after taking a part-time Front End Web Development course, and soon after decided to enroll in General Assembly's full-time immersive course. It has been true love ever since.</p>
      <p>These are a few of my favorite things:</p>
      <div class="skills">
        <div class="skills-inner">
            <%= image_tag("icons/javascript.jpg", :class =>"icon tooltipped", :alt =>"JavaScript", :data => {:position => 'bottom', :delay => 50, :tooltip =>"JavaScript"}) %>
            <%= image_tag("icons/css3.png", :class =>"icon tooltipped", :alt =>"CSS") %>
            <%= image_tag("icons/sass.png", :class =>"icon tooltipped", :alt =>"Sass") %>
            <%= image_tag("icons/html5.png", :class =>"icon tooltipped", :alt =>"HTML") %>
            <%= image_tag("icons/angular.png", :class =>"icon tooltipped", :alt =>"AngularJS") %>
            <%= image_tag("icons/ruby.png", :class =>"icon tooltipped", :alt =>"Ruby") %>
            <%= image_tag("icons/rails.png", :class =>"icon tooltipped", :alt =>"Rails") %>
            <%= image_tag("icons/node.jpg", :class =>"icon tooltipped", :alt =>"Node.js") %>
            <%= image_tag("icons/mongo.png", :class =>"icon tooltipped", :alt =>"MongoDB") %>
            <%= image_tag("icons/git.png", :class =>"icon tooltipped", :alt =>"Git") %>
            <%= image_tag("icons/sketch.png", :class =>"icon tooltipped", :alt =>"Sketch") %>
            <%= image_tag("icons/photoshop.svg", :class =>"icon tooltipped", :alt =>"Photoshop") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</container>

app/views/projects/show.html.erb
<div class="show-title">
  <%= link_to image_tag("PersonalLogo.png", :class => "show-logo"), projects_path %>
  <h1><%= @project.name %></h1>
</div>

<div class="show-links">
  <% if @project.githubURL %>
    <span class="show-button"><%= link_to "GitHub Repository", @project.githubURL %></span>
  <% end %>
  <% if @project.URL %>
    <span class="show-button"><%= link_to "View Project", @project.URL %></span>
  <% end %>
</div>

<div class="show-technologies">
  <% if @project.technology1 %>
    <span class="technology"><%= @project.technology1 %></span>
  <% end %>
  <% if @project.technology2 %>
    <span class="technology"><%= @project.technology2 %></span>
  <% end %>
  <% if @project.technology3 %>
    <span class="technology"><%= @project.technology3 %></span>
  <% end %>
  <% if @project.technology4 %>
    <span class="technology"><%= @project.technology4 %></span>
  <% end %>
  <% if @project.technology5 %>
    <span class="technology"><%= @project.technology5 %></span>
  <% end %>
</div>

<div class="show-content">
  <div class="row">
    <div class="show-images col m6 slide-left-start">
      <%= image_tag @project.image_one_url, :class => "show-image" %>
    </div>
    <div class="show-description col m6 slide-right-start">
      <%= @project.description_one %>
    </div>
  </div>
  <% if @project.description_two %>
    <div class="row">
      <div class="show-description col m6 slide-left-start">
        <%= @project.description_two %>
      </div>
      <div class="show-images col m6 slide-right-start">
        <%= image_tag @project.image_two_url, :class => "show-image" %>
      </div>
    </div>
  <% end %>
  <% if @project.description_three %>
    <div class="row">
      <div class="show-images col m6 slide-left-start">
        <%= image_tag @project.image_three_url, :class => "show-image" %>
      </div>
      <div class="show-description col m6 slide-right-start">
        <%= @project.description_three %>
      </div>
    </div>
  <% end %>
  <% if @project.description_four %>
    <div class="row">
      <div class="show-description col m6 slide-left-start">
        <%= @project.description_four %>
      </div>
      <div class="show-images col m6 slide-right-start">
        <%= image_tag @project.image_four_url, :class => "show-image" %>
      </div>
    </div>
  <% end %>
  <% if @project.description_five %>
    <div class="row">
      <div class="show-images col m6 slide-left-start">
        <%= image_tag @project.image_five_url, :class => "show-image" %>
      </div>
      <div class="show-description col m6 slide-right-start">
        <%= @project.description_five %>
      </div>
    </div>
  <% end %>
</div>